# These are populated when your service is created via the ADP Portal scaffolder. Do not change these, as they are abstracted from your service and are mandatory. They are for your reference here.
name: test-helm-only-9
namespace: ffc-demo10
workstream: ffc-demo10


# You may add further labels to identify the service or what your component does.
labels:
  component: web

# Here you can define your Priority classes, min/max replicables etc. Empty block does the HELM Library defaults.
deployment: {}

# These may be changed. See here: https://github.com/DEFRA/adp-helm-library?tab=readme-ov-file#container-template
container:
  memCpuTier: L
  port: 3001

# These may be changed. See here: https://github.com/DEFRA/adp-helm-library?tab=readme-ov-file#container-template
livenessProbe:
  path: /home9/healthz
  port: 3001
  initialDelaySeconds: 20
  periodSeconds: 10
  failureThreshold: 3
  timeoutSeconds: 5

# These may be changed. See here: https://github.com/DEFRA/adp-helm-library?tab=readme-ov-file#container-template
readinessProbe:
  path: /home9/healthy
  port: 3001
  initialDelaySeconds: 30
  periodSeconds: 10
  failureThreshold: 3
  timeoutSeconds: 5

# These are populated when your service is created via the ADP Portal scaffolder. Do not change these, as they are abstracted from your service and are mandatory. They are for your reference here.
# Your URL will be your <service-name>.<environment>.adp.defra.gov.uk for a front-end Web UI component. Azure Front Door is the Global Load Balancer, CDN and WAF. Nginx is the in-cluster ingress controller.
ingress:
  class: nginx
  endpoint: helm-9-endpoint
  server: adp.defra.gov.uk
  type: minion
  path: /home9
  defaultPath: /home9
